name: Publicar versión (build, tests, cobertura y release)

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_test_coverage:
    name: Compilar, ejecutar tests y generar cobertura
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore proyectos
        run: |
          dotnet restore src/AccessControl/AccessControl.csproj
          dotnet restore tests/AccessControl.Tests/AccessControl.Tests.csproj

      - name: Build
        run: dotnet build src/AccessControl/AccessControl.csproj --configuration Release --no-restore

      - name: Build tests
        run: dotnet build tests/AccessControl.Tests/AccessControl.Tests.csproj --configuration Release --no-restore

      - name: Test con cobertura
        run: dotnet test tests/AccessControl.Tests/AccessControl.Tests.csproj --configuration Release --no-build --collect "XPlat Code Coverage"

      - name: Instalar ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generar reporte HTML de cobertura
        env:
          PATH: ${{ env.PATH }}:~/.dotnet/tools
        run: |
          export PATH="$PATH:~/.dotnet/tools"
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      - name: Subir artefacto para GitHub Pages (cobertura)
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage-report

      - name: Subir artefacto de cobertura para release
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage-report

  deploy_pages:
    name: Publicar cobertura en GitHub Pages
    runs-on: ubuntu-latest
    needs: build_test_coverage
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  release:
    name: Crear release con artefactos
    runs-on: ubuntu-latest
    needs: build_test_coverage
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build Release
        run: dotnet build src/AccessControl/AccessControl.csproj --configuration Release --no-restore

      - name: Recopilar binarios compilados
        run: |
          mkdir -p build-artifacts
          cp -r src/AccessControl/bin/Release build-artifacts/

      - name: Descargar artefacto de cobertura
        uses: actions/download-artifact@v4
        with:
          name: coverage-html
          path: build-artifacts/coverage

      - name: Publicar GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Build y pruebas exitosas.
            Se incluye reporte de cobertura (HTML) y binarios compilados.
          files: |
            build-artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}